const mysql = require("mysql");
const fs = require("fs");
const { promisify } = require("util");

const mode = "development";
const dbConfig = mode === "development" ? {
  host: "localhost",
  user: "root",
  password: "mysql",
  connectionLimit: 100,
  port: 3306,
  database: "erp_software_db",
} : {
  host: "localhost",
  user: "erp_software_db",
  password: "erp_software_db",
  connectionLimit: 100,
  port: 3306,
  database: "erp_software_db",
};

const db = mysql.createPool(dbConfig);
const query = promisify(db.query).bind(db);


const tables = [
  `CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USER_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE PARTIES (
  PARTY_ID INT NOT NULL AUTO_INCREMENT,
  PARTY_NAME VARCHAR(80) NOT NULL,
  PARTY_ADDRESS VARCHAR(200) DEFAULT NULL,
  PARTY_PINCODE INT DEFAULT NULL,
  PARTY_MAIL VARCHAR(100) DEFAULT NULL,
  PARTY_GST VARCHAR(20) DEFAULT NULL,
  PARTY_NUMBER_1 VARCHAR(15) DEFAULT NULL,
  PARTY_NUMBER_2 VARCHAR(15) DEFAULT NULL,
  PARTY_OPENING_BALANCE FLOAT DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT 1,
  PARTY_OPENING_BALANCE_DATE DATE DEFAULT NULL,
    BILLING_NAME VARCHAR(100) DEFAULT NULL,
    TRANSPORT_NAME VARCHAR(50) DEFAULT NULL,
    TO_RECEIVE TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (PARTY_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE CASH_PARTIES (
  PARTY_ID INT NOT NULL AUTO_INCREMENT,
  BILLING_NAME VARCHAR(100) NOT NULL,
  PARTY_ADDRESS VARCHAR(200) DEFAULT NULL,
  PARTY_PINCODE INT DEFAULT NULL,
  PARTY_MAIL VARCHAR(100) DEFAULT NULL,
  PARTY_GST VARCHAR(20) DEFAULT NULL,
  PARTY_NUMBER_1 VARCHAR(15) DEFAULT NULL,
  PARTY_NUMBER_2 VARCHAR(15) DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT 1,
  PRIMARY KEY (PARTY_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE PARTIES_NOTE (
PARTY_ID INT NOT NULL,
NOTE VARCHAR(200),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTIES (PARTY_ID) ON DELETE CASCADE

) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE CASH_PARTIES_NOTE (
  CASH_PARTY_ID INT NOT NULL,
  NOTE VARCHAR(200),
      FOREIGN KEY (CASH_PARTY_ID) REFERENCES CASH_PARTIES (PARTY_ID) ON DELETE CASCADE
  
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,


  `CREATE TABLE UNIT (
    UNIT_ID INT NOT NULL AUTO_INCREMENT,
    UNIT_NAME VARCHAR(25) NOT NULL,
    UNIT_SHORT_FORM VARCHAR(10) NOT NULL,
    DISPLAY TINYINT(1) DEFAULT 1,
    PRIMARY KEY (UNIT_ID),
    UNIQUE KEY UNIT_NA (UNIT_NAME)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE GST_TYPE (
    GST_ID INT NOT NULL AUTO_INCREMENT,
    GST_PERCENTAGE INT NOT NULL,
    DISPLAY TINYINT(1) DEFAULT 1,
    PRIMARY KEY (GST_ID),
    UNIQUE KEY GST_PERC (GST_PERCENTAGE)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE HSN_DETAILS (
    HSN_ID INT NOT NULL AUTO_INCREMENT,
    HSN_CODE VARCHAR(10) NOT NULL,
    GST_REF_ID INT DEFAULT NULL,
    DISPLAY TINYINT(1) DEFAULT 1,
    PRIMARY KEY (HSN_ID),
    FOREIGN KEY (GST_REF_ID) REFERENCES GST_TYPE (GST_ID) ON DELETE SET NULL
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE ITEMS (
    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    ITEM_NAME VARCHAR(255) NOT NULL,
    ITEM_CODE VARCHAR(50) DEFAULT NULL,
    ITEM_GST_TYPE_ID INT DEFAULT NULL,
    ITEM_BRAND VARCHAR(100) DEFAULT NULL,
    ITEM_PURCHASE_PRICE FLOAT DEFAULT NULL,
    ITEM_PURCHASE_DISCOUNT FLOAT DEFAULT NULL,
    ITEM_PURCHASE_QUANTITY FLOAT DEFAULT NULL,
    ITEM_SALES_PRICE FLOAT DEFAULT NULL,
    ITEM_SALES_DISCOUNT FLOAT DEFAULT NULL,
    ITEM_SALES_QUANTITY FLOAT DEFAULT NULL,
    ITEM_DEFAULT_UNIT_ID INT DEFAULT NULL,
    DISPLAY TINYINT(1) DEFAULT 1,
    ITEM_OPENING_QTY INT DEFAULT NULL,
    ITEM_HSN_ID INT DEFAULT NULL,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (ITEM_GST_TYPE_ID) REFERENCES GST_TYPE (GST_ID),
    FOREIGN KEY (ITEM_DEFAULT_UNIT_ID) REFERENCES UNIT (UNIT_ID),
    FOREIGN KEY (ITEM_HSN_ID) REFERENCES HSN_DETAILS (HSN_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `
CREATE TABLE ITEM_DESCRIPTIONS(
ITEM_ID INT NOT NULL,
ITEM_DESCRIPTION VARCHAR(250),
FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE BILL_SERIES (
    BILL_SERIES_ID INT NOT NULL AUTO_INCREMENT,
    BILL_SERIES VARCHAR(25) NOT NULL,
    DISPLAY TINYINT(1) DEFAULT 1,
    PREFIX TINYINT(1) NOT NULL,
    PRIMARY KEY (BILL_SERIES_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE BILL_DETAILS (
    BILL_DETAILS_ID INT NOT NULL AUTO_INCREMENT,
    BILL_ID INT NOT NULL,
    BILL_TYPE VARCHAR(20) DEFAULT NULL,
    PACKINGS INT DEFAULT NULL,
    SHIPPING_ADDRESS VARCHAR(150) DEFAULT NULL,
    TRANSPORT VARCHAR(70) DEFAULT NULL,
    PLUS_TAX TINYINT(1) DEFAULT 0 NOT NULL,
    SUBTOTAL FLOAT DEFAULT NULL,
    ROUND_OFF FLOAT DEFAULT NULL,
    FREIGHT FLOAT DEFAULT NULL,
    DISCOUNT_PERC FLOAT DEFAULT NULL,
    TOTAL FLOAT DEFAULT NULL,
    AMOUNT_SETTLED FLOAT DEFAULT NULL,
    PRIMARY KEY (BILL_DETAILS_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE SALES_BILL (
    SALES_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    BILL_SERIES_ID INT DEFAULT NULL,
    BILL_NUMBER VARCHAR(10) NOT NULL,
    BILL_DATE DATETIME NOT NULL,
    BILL_CREATED_DATE DATETIME NOT NULL,
    BILL_LAST_UPDATED DATETIME NOT NULL,
    BILL_YEAR INT NOT NULL,
    CASH_ENTRY TINYINT(1) DEFAULT NULL,
    PRIMARY KEY (SALES_ID),
    FOREIGN KEY (BILL_SERIES_ID) REFERENCES BILL_SERIES (BILL_SERIES_ID),
    CONSTRAINT CHK_BILL_NUMBER_DIGITS CHECK (BILL_NUMBER REGEXP '^[0-9]+$')
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE BILL_ITEMS (
    BILL_ITEM_ID INT NOT NULL AUTO_INCREMENT,
    BILL_DETAILS_ID INT NOT NULL,
    BILL_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    QUANTITY FLOAT DEFAULT NULL,
    UNIT_ID INT DEFAULT NULL,
    PRICE FLOAT DEFAULT NULL,
    DISCOUNT FLOAT DEFAULT NULL,
    GST_ID INT DEFAULT NULL,
    AMOUNT INT DEFAULT NULL,
    BILL_TYPE VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (BILL_ITEM_ID),
    FOREIGN KEY (BILL_DETAILS_ID) REFERENCES BILL_DETAILS (BILL_DETAILS_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID) ON DELETE SET NULL,
    FOREIGN KEY (GST_ID) REFERENCES GST_TYPE (GST_ID) ON DELETE SET NULL
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE BILL_NOTE (
    BILL_NOTE_ID INT NOT NULL AUTO_INCREMENT,
    BILL_DETAILS_ID INT NOT NULL,
    BILL_ID INT NOT NULL,
    BILL_TYPE VARCHAR(20) DEFAULT NULL,
    BILL_NOTE VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (BILL_NOTE_ID),
    FOREIGN KEY (BILL_DETAILS_ID) REFERENCES BILL_DETAILS (BILL_DETAILS_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE USER_COMPANY_DETAILS (
    COMPANY_ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_NAME VARCHAR(70) NOT NULL,
    COMPANY_ADDRESS VARCHAR(200) DEFAULT NULL,
    COMPANY_PINCODE INT DEFAULT NULL,
    COMPANY_PHONE_NUMBER VARCHAR(15) DEFAULT NULL,
    COMPANY_EMAIL VARCHAR(70) DEFAULT NULL,
    COMPANY_GSTIN VARCHAR(15) DEFAULT NULL,
    STATE_CODE VARCHAR(2) DEFAULT NULL,
    USER_ID INT DEFAULT NULL,
    PRIMARY KEY (COMPANY_ID),
    UNIQUE (USER_ID, COMPANY_NAME),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE USER_TOKENS (
    TOKEN_ID INT NOT NULL AUTO_INCREMENT,
    USER_TOKEN VARCHAR(255) NOT NULL UNIQUE,
    TOKEN_EXPIRY_TIME DATETIME NOT NULL,
    DEVICE_IP VARCHAR(30),
    USER_ID INT NOT NULL,
    PRIMARY KEY (TOKEN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,


  `CREATE TABLE PAYMENT_MODES (
  PAYMENT_MODE_ID INT NOT NULL,
  MODE_NAME VARCHAR(100) DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (PAYMENT_MODE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE PAYMENTS (
  PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
  PAYMENT_MODE_ID INT NOT NULL,
  AMOUNT FLOAT NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  PAYMENT_TYPE ENUM('IN', 'OUT', 'P2P') NOT NULL,
  PRIMARY KEY (PAYMENT_ID),
  CONSTRAINT CHK_AMOUNT_NON_ZERO CHECK (AMOUNT <> 0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,


  `CREATE TABLE P2PTRANSFER (
  PAYMENT_ID INT NOT NULL,
  FROM_PARTY_ID INT DEFAULT NULL,
  TO_PARTY_ID INT DEFAULT NULL,
   CONSTRAINT CHK_NOT_SAME_PARTY CHECK (FROM_PARTY_ID <> TO_PARTY_ID),
FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (PAYMENT_ID),
  FOREIGN KEY (FROM_PARTY_ID) REFERENCES PARTIES (PARTY_ID),
  FOREIGN KEY (TO_PARTY_ID) REFERENCES PARTIES (PARTY_ID) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,


  `CREATE TABLE PAYMENT_ALLOCATION (
    PAYMENT_ALLOCATION_ID INT NOT NULL AUTO_INCREMENT,
    PAYMENT_ID INT NOT NULL,
    AMOUNT FLOAT NOT NULL,
    BILL_DETAILS_ID INT NOT NULL,
    BILL_ID INT NOT NULL,
    BILL_TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY (PAYMENT_ALLOCATION_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (PAYMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (BILL_DETAILS_ID) REFERENCES BILL_DETAILS (BILL_DETAILS_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_AMOUNT_NON_ZERO2 CHECK (AMOUNT <> 0)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE DEFAULT_VALUES (
  DEFAULT_UNIT_ID INT NOT NULL,
  DEFAULT_GST_TYPE_ID INT NOT NULL,
  DEFAULT_PAYMENT_MODE_ID INT NOT NULL,
  DEFAULT_HSN_ID INT NOT NULL,
  DEFAULT_BILL_SERIES_ID INT NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE CATEGORIES(
  CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(127),
  PRIMARY KEY (CATEGORY_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  //   `CREATE TABLE ITEM_CATEGORY_RELATION(
  //   PARENT_ID INT NOT NULL,
  //   CHILD_ID INT NOT NULL,
  //   FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  //   FOREIGN KEY (CHILD_ID) REFERENCES ITEMS (ITEM_ID)
  // ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  //   `CREATE TABLE CATEGORY_CATEGORY_RELATION(
  //   PARENT_ID INT NOT NULL,
  //   CHILD_ID INT NOT NULL,
  //   FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  //   FOREIGN KEY (CHILD_ID) REFERENCES CATEGORIES (CATEGORY_ID)
  // ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE ITEM_CATEGORY_RELATION (
  PARENT_ID INT NOT NULL,
  CHILD_ID INT NOT NULL,
  PRIMARY KEY (PARENT_ID,CHILD_ID), 
  CONSTRAINT ITEM_CATEGORY_RELATION_IBFK_1 FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  CONSTRAINT ITEM_CATEGORY_RELATION_IBFK_2 FOREIGN KEY (CHILD_ID) REFERENCES ITEMS (ITEM_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE CATEGORY_CATEGORY_RELATION (
  PARENT_ID INT NOT NULL,
  CHILD_ID INT NOT NULL,
  PRIMARY KEY (PARENT_ID,CHILD_ID), 
  CONSTRAINT CHK_DIFFERENT_IDS CHECK (PARENT_ID <> CHILD_ID),
  CONSTRAINT CATEGORY_CATEGORY_RELATION_IBFK_1 FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  CONSTRAINT CATEGORY_CATEGORY_RELATION_IBFK_2 FOREIGN KEY (CHILD_ID) REFERENCES CATEGORIES (CATEGORY_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE CATEGORIES_PHOTO_PATH(
  CATEGORY_ID INT NOT NULL ,
  PHOTO_PATH_ID INT NOT NULL ,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
  FOREIGN KEY (PHOTO_PATH_ID) REFERENCES DOCUMENT_PATH (DOCUMENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE ITEM_PHOTO_PATH(
  ITEM_ID INT NOT NULL ,
  PHOTO_PATH_ID INT NOT NULL ,
  FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
  FOREIGN KEY (PHOTO_PATH_ID) REFERENCES DOCUMENT_PATH (DOCUMENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,

  `CREATE TABLE DOCUMENT_PATH(
  DOCUMENT_ID INT NOT NULL AUTO_INCREMENT ,
  DOC_PATH VARCHAR(255),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES CATEGORIES (CATEGORY_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;`,





];



const currentDate = new Date();
currentDate.setDate(currentDate.getDate() + 30);
const formattedDate = currentDate.toLocaleDateString('en-CA').slice(0, 19).replace('T', ' ');

const datas = [
  {
    query: `INSERT INTO USERS(USER_NAME, USER_PASSWORD) VALUES(?, ?); `,
    values: ["JJ", "asd"],
  },
  {
    query: `INSERT INTO USER_TOKENS(USER_TOKEN, TOKEN_EXPIRY_TIME, DEVICE_IP, USER_ID) VALUES(?,?,?,?)`,
    values: ["62566b7790cefd73549c163ece2ffd72dff248eeea9d09cd959828d6acdeb8d2f3ec573a03f4908395e6f549368f70932cbcef22af6ce9d6a26fbb944a825cc213cfe19a5a08840df9dde150349518b8", formattedDate, "::1", 1]
  },
  // {
  //   query: `INSERT INTO users(USER_NAME, USER_PASSWORD) VALUES(?, ?); `,
  //   values: ["JJ", "asd"],
  // },
  // {
  //   query: `INSERT INTO users(USER_NAME, USER_PASSWORD) VALUES(?, ?); `,
  //   values: ["JJ", "asd"],
  // },

];

async function createTables(tables) {
  try {
    for (const table of tables) {
      await query(table);
    }
    await insertData(datas);
  } catch (err) {
    console.error("Error creating tables or inserting data:", err);
  }
}

async function insertData(datas) {
  try {
    for (const data of datas) {
      await query(data.query, data.values);
    }
    console.info("no prob");

  } catch (err) {
    console.error("Error inserting data:", err);
  }
}

async function writeFile() {
  try {
    const out = tables.join('\n');
    await fs.promises.writeFile("./starters/db.txt", out);
    console.info("File created successfully");
  } catch (err) {
    console.error("Error writing file:", err);
  }
}

(async () => {
  await createTables(tables);
  await writeFile();
})();
